#DBに関する設定
# デプロイにあたって
# localhost → database-1.c7nemfuoe0vm.us-east-2.rds.amazonaws.com
# username, password変更
spring:
  datasource:
    #MySql用
    #url: jdbc:mysql://localhost:3306/TaskTime?serverTimezone=Asia/Tokyo
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #password: lovekayo
    
    #PostgreSql用
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/task
    #username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://kcjnpjcpzimsah:574c784f73abfdbae5006073c822eb04200976bbb98ee3d4c7310619332179b2@ec2-44-196-174-238.compute-1.amazonaws.com:5432/dafbubeqeh60ra
    username: kcjnpjcpzimsah
    password: 574c784f73abfdbae5006073c822eb04200976bbb98ee3d4c7310619332179b2

  sql:
    init:
      encoding: UTF-8
      mode: always

#GoogleOauth2.0に関する設定
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
             #↓本番環境(AWS内)ではコメントアウトを外す
            redirect-uri: http://mk-100588-taskm.herokuapp.com/login/oauth2/code/google
            #redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
            - email
            - https://www.googleapis.com/auth/userinfo.email
            - profile
            - https://www.googleapis.com/auth/userinfo.profile
            - openid
            - https://www.googleapis.com/auth/calendar

#Tomcatのポート番号
#AWS環境では8080なので以下コメントアウトする
#server:
    #port: 8080

#Log Level
logging:
  file:
    name: ./logs/tasktime.log
  level:
    '[com.example]': debug
    #S'[org.springframework.web]': DEBUG
